const POST_ADMINISTRATIVO = "POST_ADMINISTRATIVO";
const POST_TUTOR = "POST_TUTOR";
const POST_PRECEPTOR = "POST_PRECEPTOR";
const POST_SUPERVISOR = "POST_SUPERVISOR";





module.exports = {POST_TUTOR, POST_ADMINISTRATIVO, POST_PRECEPTOR, POST_SUPERVISOR};